name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  font_awesome_flutter: ^9.2.0
  geolocator: ^8.0.5
  http: ^0.13.4
  slugify: ^2.0.0
  google_maps_flutter: ^2.1.1
  fmaps: ^0.0.2
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900

  - family: Spartan MB Regular
    fonts:
      - asset: fonts/SpartanMB-Regular.otf

  - family: Spartan MB Medium
    fonts:
      - asset: fonts/SpartanMB-Medium.otf